# Generated by Django 3.0.8 on 2020-12-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'valid'), (1, 'active'), (2, 'expired')], default=((0, 'valid'), (1, 'active'), (2, 'expired')))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='invest.Plan')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
