# Generated by Django 3.0.8 on 2020-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20201203_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
