# Generated by Django 3.0.8 on 2020-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_coupon_expire_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ac_name', models.CharField(max_length=100)),
                ('ac_num', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=20)),
                ('review', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
