# Generated by Django 3.0.8 on 2020-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
