# Generated by Django 3.0.8 on 2020-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='referal',
            name='num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
