# Generated by Django 3.0.8 on 2020-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_auto_20201208_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ref_money',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='w_money',
        ),
        migrations.AddField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ref_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
    ]
